services:
  aspireapptest.apiservice:
    image: ${DOCKER_REGISTRY-}coffeshop.api
    container_name: api
    build:
      context: .
      dockerfile: AspireAppTest.ApiService/Dockerfile
    ports:
        - 8081:8081
    environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://coffeeshop-dashboard:18889
    networks:
      - otel

  conffeshop.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
        - 18888:18888
    networks:
      - otel
  
networks:
    otel:
        driver: bridge